@echo off

start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat
start c:\desk.bat